version: "3.6"
services:
  db:
    image: mysql:8.0.18
    container_name: mysqldb
    ports: 
      - 3300:3300
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=user_database
    networks: 
      - book-nw
    volumes:
      - ./mysqldb:/var/lib/mysql
  
  eureka:
      image: discovery-book-service
      build: ./BookAppDiscoveryService
      container_name: book-discovery
      ports: 
        - 8000:8000
      networks: 
      - book-nw
  zuul:
    image: zuul-service-book
    build: ./BookAppApiZuulAPIGateway
    container_name: zuul-bridge
    ports: 
      - 8002:8002
    depends_on: 
      - db
      - eureka
    networks: 
      - book-nw 
   
  book-service:
      image: book-service
      build: ./BookAppApiBooks
      container_name: book-service
      ports: 
        - 8001:8001
      depends_on: 
        - db
        - eureka
        - zuul
      networks: 
        - book-nw

networks:
  book-nw:
    name: book-nw