eureka.client.service-url.defaultZone: "http://localhost:9050/eureka"

# enabling debug
logging.level.org.springframework.web: DEBUG

#including all the endpoints of actuator
management.endpoints.web.exposure.include: *