eureka:
    client:
        service-url:
            defaultZone: http://eureka-discovery:8761/eureka
logging:
    level:
        org:
            springframework:
                web: DEBUG
management:
    endpoints:
        web:
            exposure:
                include: '*'
